included:
  - apps/ios/LifeIsAMovie

excluded:
  - apps/ios/LifeIsAMovie/Resources

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
