included:
  - LifeIsAMovie

excluded:
  - LifeIsAMovie.xcodeproj

disabled_rules:
  - trailing_comma

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - discouraged_optional_boolean
  - force_unwrapping
  - implicitly_unwrapped_optional
  - modifier_order

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
