name: LifeIsAMovie
options:
  bundleIdPrefix: com.notiablank
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
targets:
  LifeIsAMovie:
    type: application
    platform: iOS
    sources:
      - LifeIsAMovie
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notiablank.lifeisamovie
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
    scheme:
      testTargets:
        - LifeIsAMovieTests
  LifeIsAMovieTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LifeIsAMovieTests
    dependencies:
      - target: LifeIsAMovie
